    /* ================= W4 · MDPs ================= */
    const MDPQ = [
      { q: 'An MDP is a sequential decision making problem for an environment that is…', a: 'Fully observable but stochastic',
        c: ['Fully observable but stochastic', 'Partially observable but deterministic', 'Fully observable and deterministic', 'Partially observable and stochastic'],
        e: 'MDPs relax <strong>exactly one</strong> of search’s two assumptions. You still always know which state you are in; what you no longer know is where an action will take you. Dropping observability too gives a POMDP.' },
      { q: 'What does the <strong>Markov property</strong> say?', a: 'The next state depends only on the current state, not the history',
        c: ['The next state depends only on the current state, not the history', 'The transition probabilities never change over time', 'Every state has the same number of actions', 'Rewards are always negative'],
        e: 'Formally P(S<sub>t+1</sub>|S<sub>t</sub>,…,S<sub>0</sub>) = P(S<sub>t+1</sub>|S<sub>t</sub>). Don’t confuse it with <em>stationarity</em>, which is the separate assumption that the probabilities don’t change over time.' },
      { q: 'What does it mean that an MDP’s probability distributions are <strong>stationary</strong>?', a: 'They do not change over time',
        c: ['They do not change over time', 'They do not depend on the history', 'They sum to 1', 'They are the same for every action'],
        e: 'Moving Up is 0.8-reliable on turn 1 and on turn 400. Without this, the best action would depend on <em>when</em> as well as <em>where</em>, and a single utility per state could not exist.' },
      { q: 'What does <code>T(s, a, s′)</code> encode?', a: 'P(s′ | s, a)', c: ['P(s′ | s, a)', 'P(s, a | s′)', 'R(s′) − R(s)', 'U(s′) − U(s)'],
        e: 'The transition model: the probability of landing in s′ given that you are in s and take a. One probability distribution <strong>per state–action pair</strong>.' },
      { q: 'A policy must be complete, optimal, stationary and <strong>proper</strong>. What does <em>proper</em> mean?', a: 'Guaranteed to reach a terminal state',
        c: ['Guaranteed to reach a terminal state', 'Defined for every state', 'Dependent only on the current state', 'Gives the best action for each state'],
        e: 'Complete = covers all states · optimal = best action for s · stationary = depends only on the current state · <strong>proper = guaranteed to reach a terminal state</strong>. An improper policy circles forever and never collects the +1.' },
      { q: 'What is the discount factor γ for?', a: 'Valuing current rewards over future ones',
        c: ['Valuing current rewards over future ones', 'Scaling the transition probabilities', 'Setting the error tolerance', 'Weighting the step cost against the goal reward'],
        e: 'It also makes Σγ<sup>t</sup>R finite even for an infinite run. With γ = 1 the sum only converges because the policy is <em>proper</em> and the run therefore ends.' },
      { q: 'Why is a fixed sequence of actions not a good solution to an MDP?', a: 'It stops being valid as soon as an action does not do what was asked',
        c: ['It stops being valid as soon as an action does not do what was asked', 'It is too long to compute', 'It cannot include the goal state', 'Sequences cannot express discounting'],
        e: 'This is the reason the answer becomes a <strong>policy</strong> — an action for <em>every</em> state — rather than a plan. It stays valid wherever you end up.' },
      { q: '<code>E[U] = Σ<sub>c∈C</sub> P(c)U(c)</code> is the definition of…', a: 'Expected value', c: ['Expected value', 'Bayes’ rule', 'The Bellman equation', 'A joint probability'],
        e: 'In words: the sum over c of the probability of c times the utility of c. The coin bet gives 0.5×0 + 0.5×5 = <strong>2.5</strong> — a value you can never actually receive on a single throw.' },
      { q: 'Bayes’ rule states that P(a|b) equals…', a: 'P(a, b) / P(b)', c: ['P(a, b) / P(b)', 'P(a, b) / P(a)', 'P(a) × P(b)', 'P(b|a) × P(b)'],
        e: 'Dividing by P(b) ≤ 1 makes the result bigger, so <strong>P(a|b) ≥ P(a,b)</strong> always: the joint asks you to get lucky twice, the conditional hands you one for free.' },
      { q: 'In <code>E[U|s,a] = Σ<sub>s′</sub> P(s′|s,a)U(s′)</code>, what is the sum taken over?', a: 'All neighbour states s′ the action could lead to',
        c: ['All neighbour states s′ the action could lead to', 'All actions available in s', 'All states in the MDP', 'All time steps until termination'],
        e: 'Exactly like summing over both sides of a coin — you must include <strong>every</strong> outcome, including the ones you did not intend, or the probabilities will not add to 1.' },
      { q: 'In the Bellman update, what do you <strong>max</strong> over and what do you <strong>average</strong> over?', a: 'Max over actions, average over outcomes',
        c: ['Max over actions, average over outcomes', 'Max over outcomes, average over actions', 'Max over both', 'Average over both'],
        e: 'The agent chooses its action, so it takes the best; the world chooses the outcome, so we take the expectation. <strong>Max over your options, average over the world’s.</strong>' },
      { q: 'How is U initialised in value iteration?', a: '0 everywhere, except end states where U(s) = R(s)',
        c: ['0 everywhere, except end states where U(s) = R(s)', '0 everywhere including end states', 'R(s) everywhere', 'Randomly'],
        e: 'The terminals are the only states whose utility is known from the start, and they are the seed from which value spreads outwards, roughly one square per iteration.' },
      { q: 'When does value iteration stop?', a: 'When δ < ε(1 − γ)/γ',
        c: ['When δ < ε(1 − γ)/γ', 'When δ < ε', 'When the policy stops changing', 'After exactly |S| iterations'],
        e: 'δ is the largest change any state saw this sweep; ε is the error you will tolerate in the final utilities. Note the threshold → 0 as γ → 1, which is why near-1 discounts are so expensive.' },
      { q: 'How do you get the policy once the utilities have converged?', a: 'π(s) = arg max<sub>a</sub> Σ<sub>s′</sub> P(s′|s,a)U(s′)',
        c: ['π(s) = arg max<sub>a</sub> Σ<sub>s′</sub> P(s′|s,a)U(s′)', 'π(s) = max<sub>a</sub> Σ<sub>s′</sub> P(s′|s,a)U(s′)', 'π(s) = R(s) + γ max<sub>a</sub> Σ<sub>s′</sub> P(s′|s,a)U(s′)', 'π(s) = the neighbour with the highest U'],
        e: '<code>max</code> returns the best <em>value</em>, <code>arg max</code> the <em>action</em> that achieved it. R(s) and γ drop out because they are the same for every action and so cannot change which one wins.' },
      { q: 'As the discount factor γ approaches 1, the number of iterations required…', a: 'Blows up',
        c: ['Blows up', 'Falls to zero', 'Stays roughly constant', 'Depends only on the error tolerance'],
        e: 'Figure 17.5(b): roughly 10–20 iterations at γ = 0.5, rising steeply near 1. Larger γ means distant rewards never fade, so information must cross the whole state space before anything settles. The error tolerance matters far less.' },
      { q: 'With R(s) = −1.65 on the standard grid, why does the policy at (3,2) point <em>into</em> the −1 terminal?', a: 'Every extra step costs more than the −1 penalty',
        c: ['Every extra step costs more than the −1 penalty', 'The transition model makes Up impossible', 'It is a mistake in the lectures', 'The +1 is unreachable from there'],
        e: 'Life is agony, so ending it quickly is worth more than the penalty for ending it badly. As R rises from very negative to positive, the agent goes <strong>suicidal → hurried → cautious → immortal</strong> — with the algorithm untouched.' },
      { q: 'With R(s) &gt; 0, what does the optimal policy do?', a: 'Avoids both terminals and never ends',
        c: ['Avoids both terminals and never ends', 'Runs straight to the +1', 'Runs to whichever terminal is nearest', 'Is undefined'],
        e: 'Existing is profitable, so the agent collects reward forever. With γ = 1 the utilities diverge — the sum Σγ<sup>t</sup>R has no limit.' },
      { q: 'On the standard grid with R = −0.04, the policy at (4,1) — directly below the −1 — points…', a: 'Left, away from the goal',
        c: ['Left, away from the goal', 'Up, towards the +1', 'Right, into the wall', 'Down, into the wall'],
        e: 'Going Up is the short route, but a 10% sideways slip drops you in the −1. The long way round is worth the extra steps. <strong>No deterministic search algorithm could ever produce this</strong>, because in a deterministic world you never enter a square by accident.' }
    ];
    MDPQ.forEach(d => QZ_GEN.push({ topic: 'mdp', make: () => ({
      topic: 'MDP · concepts', kind: 'choice', prompt: d.q, choices: d.c.slice(), answer: d.a,
      check: textCheck(d.a), explain: d.e }) }));
