  /* ============================================================
     MOCK EXAM — data-driven, auto-marking
     ============================================================ */
  const mockQuestionBank = [
  // ===================== WEEK 1: Core concepts, LDE, syscalls =====================
  { type:'multi', topic:'W1 · OS role', q:'Which of these are jobs an operating system performs?', opts:['Loading programs into memory','Scheduling processes onto the CPU','Managing memory allocation','Compiling source code into machine code'], correct:[0,1,2], explain:'The OS handles loading, scheduling, memory, I/O, security and control. Compiling source to machine code is the job of a <em>compiler</em>, a normal user program, not the OS.' },
  { type:'single', topic:'W1 · Definition', q:'Which best captures what an operating system fundamentally does?', opts:['Translates high-level code to machine code','Securely multiplexes (shares) hardware among programs and users','Interprets bytecode at runtime','Provides a graphical user interface'], correct:[1], explain:'At its core the OS <strong>securely multiplexes</strong> the hardware \u2014 sharing CPU, memory and devices among multiple programs/users while keeping them isolated. The GUI is optional; translation/interpretation are compiler/VM jobs.' },
  { type:'multi', topic:'W1 · Concurrency', q:'Which statements about concurrency vs parallelism are true?', opts:['Concurrency is about interleaved execution whose ordering is uncontrolled','Parallelism requires multiple CPU cores to be literal','On a single core, threads can still run concurrently','Parallelism and concurrency mean exactly the same thing'], correct:[0,1,2], explain:'Concurrency = multiple tasks in progress with uncontrolled interleaving (possible even on one core). Parallelism = literally simultaneous, needing multiple cores. They are related but <strong>not</strong> the same.' },
  { type:'multi', topic:'W1 · LDE', q:'Limited direct execution means the OS\u2026', opts:['Runs user code directly on the real hardware at full speed','Interprets each user instruction for safety','Keeps control via user/kernel mode and interrupts','Lets the program run but can regain control via a timer interrupt'], correct:[0,2,3], explain:'LDE runs programs <em>directly</em> on hardware (not interpreted/translated) but stays in control through user/kernel mode restrictions and interrupts (e.g. a timer interrupt for preemption).' },
  { type:'single', topic:'W1 · Mode', q:'Why does a system call use a small number rather than the memory address of the OS routine?', opts:['Numbers are faster to compare than addresses','The OS code location is protected/abstracted; the number indexes a kernel-controlled table','Addresses change every time the program runs','User programs cannot store 64-bit addresses'], correct:[1], explain:'The kernel\u2019s code is protected and its layout is abstracted away. The syscall number indexes a table the kernel controls, so the OS can relocate its internals without breaking programs, and user code can\u2019t jump to arbitrary kernel addresses.' },
  { type:'multi', topic:'W1 · Trap table', q:'Regarding the trap table, which are true?', opts:['It is set up at boot time in kernel mode','It tells the hardware where each interrupt/trap handler is','Installing it is a privileged operation','User programs may freely install their own trap table'], correct:[0,1,2], explain:'The trap table is installed at boot (kernel mode) and maps trap/interrupt numbers to handler addresses. Installing it is <strong>privileged</strong> \u2014 if user code could set it, it could hijack the machine.' },
  { type:'multi', topic:'W1 · Syscall instr', q:'Which instructions might plausibly perform a system call?', opts:['<code>int 0x80</code>','<code>syscall</code>','<code>jmp 0x80017fab</code>','<code>add %rax, %rbx</code>'], correct:[0,1], explain:'<code>int 0x80</code> (32-bit Linux) and <code>syscall</code> (x86-64) trap into the kernel with a mode switch. A plain <code>jmp</code> or <code>add</code> stays in user mode \u2014 no trap, no mode switch.' },
  { type:'single', topic:'W1 · Control', q:'On a cooperative (non-preemptive) system, how does the OS regain control from a running process?', opts:['A timer interrupt always fires','Only when the process makes a syscall or yields','It cannot, ever','By forcibly preempting after a fixed quantum'], correct:[1], explain:'Cooperative scheduling relies on the process voluntarily yielding or making a syscall (a software interrupt). With no timer-based preemption, a CPU-bound process making no syscalls keeps the CPU indefinitely \u2014 reboot is the only recourse.' },
  { type:'multi', topic:'W1 · Address space', q:'A process\u2019s address space\u2026', opts:['Is the set of memory addresses it can use','Is virtual, mapped to physical memory by the OS/hardware','Is shared identically with every other process by default','Gives the illusion that the process has memory to itself'], correct:[0,1,3], explain:'Each process gets its own virtual address space, mapped to physical memory by the MMU, giving the illusion of private memory. Address spaces are <strong>not</strong> shared by default \u2014 that\u2019s the isolation guarantee.' },
  { type:'single', topic:'W1 · User/kernel', q:'What happens to the CPU mode during a system call?', opts:['Stays in user mode throughout','Switches to kernel mode, then back to user mode on return','Switches to kernel mode permanently','Disables interrupts forever'], correct:[1], explain:'A syscall traps into <strong>kernel mode</strong> to run the privileged handler, then returns to user mode (return-from-trap). The mode switch is exactly what makes a syscall different from an ordinary procedure call.' },

  // ===================== WEEK 2: Processes & scheduling =====================
  { type:'multi', topic:'W2 · Process vs program', q:'Which statements about programs and processes are true?', opts:['A program is a passive file; a process is a running instance','Running the same program twice creates two processes','A process is just another name for a program','One program can have many concurrent processes'], correct:[0,1,3], explain:'A program is a static file on disk; a process is a running instance with its own memory and state. The same program can have many processes. They are <strong>not</strong> synonyms.' },
  { type:'multi', topic:'W2 · Memory layout', q:'Which memory regions are loaded directly from the program\u2019s binary file?', opts:['Text (code) segment','Data segment (initialised globals)','Heap','Stack'], correct:[0,1], explain:'Text and data come from the executable. The heap and stack are created at runtime by the OS \u2014 the heap starts empty and the stack grows as calls are made.' },
  { type:'single', topic:'W2 · PCB', q:'Which of these would the OS store in a Process Control Block (PCB)?', opts:['The source code of the program','The process state, program counter and saved registers','The compiler used to build it','The user\u2019s password'], correct:[1], explain:'The PCB holds per-process bookkeeping: PID, state, program counter, saved registers, memory info, open files, etc. \u2014 everything needed to suspend and resume the process.' },
  { type:'single', topic:'W2 · Scheduler', q:'What are the candidate tasks a scheduler chooses from?', opts:['All tasks','Tasks in the waiting (blocked) state','Tasks in the runnable/ready state','Only newly created tasks'], correct:[2], explain:'The scheduler picks among <strong>ready/runnable</strong> tasks. Waiting tasks are blocked (e.g. on I/O) and aren\u2019t candidates until their event completes.' },
  { type:'single', topic:'W2 · Burst time', q:'A process\u2019s burst time is best described as\u2026', opts:['The exact time until the next hardware interrupt','A running estimate of CPU time before it next requests I/O','The total lifetime of the process','The time spent waiting in the ready queue'], correct:[1], explain:'Burst time is an <strong>estimate</strong> of how long the process will use the CPU before blocking on I/O. Schedulers like SJF/STCF use these estimates.' },
  { type:'multi', topic:'W2 · Context switch', q:'Which statements about context switches are true?', opts:['They involve saving and restoring register state','They are pure overhead (no useful work for the program)','They are free on modern hardware','They occur when switching between processes/threads'], correct:[0,1,3], explain:'A context switch saves one task\u2019s registers and restores another\u2019s \u2014 necessary but pure overhead. It is <strong>not</strong> free; it costs time (and cache effects).' },
  { type:'multi', topic:'W2 · FCFS', q:'Which are true of First-Come-First-Served scheduling?', opts:['It is non-preemptive','It can suffer the convoy effect','It guarantees the shortest average waiting time','A long job can delay many short jobs behind it'], correct:[0,1,3], explain:'FCFS is non-preemptive and prone to the convoy effect (short jobs stuck behind a long one). <strong>SJF</strong>, not FCFS, minimises average waiting time.' },
  { type:'single', topic:'W2 · SJF', q:'Shortest Job First scheduling optimises for\u2026', opts:['The best (minimum) average waiting/turnaround time','The best response time','Fairness between all jobs','Maximum CPU utilisation only'], correct:[0], explain:'SJF gives provably optimal average turnaround/waiting time, but can <strong>starve</strong> long jobs and needs burst-time estimates. Round Robin is the one that optimises response time.' },
  { type:'multi', topic:'W2 · Round Robin', q:'Which statements about Round Robin are true?', opts:['It is preemptive, relying on a timer interrupt','It optimises response time / fairness','A very large time quantum makes it behave like FCFS','A very small quantum eliminates context-switch overhead'], correct:[0,1,2], explain:'RR preempts via a timer, giving good response/fairness. A huge quantum \u2192 FCFS-like. A <em>tiny</em> quantum <strong>increases</strong> overhead (more switches), it doesn\u2019t eliminate it.' },
  { type:'multi', topic:'W2 · Non-preemptive', q:'On an OS with only non-preemptive scheduling, which are true?', opts:['Round Robin could be available','FCFS could be available','A running task must yield or it keeps the CPU','Priority scheduling is impossible'], correct:[1,2], explain:'RR needs preemption, so it can\u2019t exist here. FCFS fits naturally. Without preemption a task must yield/do I/O to give up the CPU. Priority scheduling <strong>is</strong> still possible (pick highest-priority ready task when one yields).' },
  { type:'multi', topic:'W2 · Metrics', q:'Which pairs of (metric, meaning) are correct?', opts:['Turnaround time = completion \u2212 arrival','Response time = first-run \u2212 arrival','Waiting time = turnaround \u2212 burst','Response time = completion \u2212 first run'], correct:[0,1,2], explain:'Turnaround = completion\u2212arrival; response = (first time it runs)\u2212arrival; waiting = turnaround\u2212burst. The last option is wrong.' },
  { type:'single', topic:'W2 · Trade-off', q:'The fundamental scheduling trade-off is between\u2026', opts:['Turnaround time and response time','CPU and memory','Throughput and security','Fairness and correctness'], correct:[0], explain:'Optimising turnaround (SJF/STCF) hurts response and fairness; optimising response (RR) hurts turnaround. You cannot maximise both at once.' },
  { type:'multi', topic:'W2 · Threads', q:'Which statements about threads are true?', opts:['Threads of one process share the heap','Each thread has its own stack','Threads of one process share the same code','Each thread has its own copy of all global variables'], correct:[0,1,2], explain:'Threads share the process\u2019s code, data and heap, but each has its <strong>own stack</strong>. Globals are shared (on the heap/data), not copied \u2014 which is exactly why races happen.' },
  { type:'single', topic:'W2 · States', q:'A process moves from \u201crunning\u201d to \u201cwaiting\u201d when\u2026', opts:['Its time quantum expires','It requests I/O and must block','It is created','It finishes execution'], correct:[1], explain:'Blocking on I/O moves running \u2192 waiting. Quantum expiry moves running \u2192 ready. Finishing moves running \u2192 terminated.' },

  // ===================== WEEK 3: Virtual memory & translation =====================
  { type:'multi', topic:'W3 · Address binding', q:'The address-binding problem is about\u2026', opts:['Programs being loaded into memory','Multiple programs sharing the same physical address space safely','Programs sharing the same virtual address space','Choosing a scheduling algorithm'], correct:[0,1], explain:'Address binding concerns loading programs and letting many of them coexist in one <strong>physical</strong> address space without clashing. It is not about scheduling, nor about sharing a single virtual space.' },
  { type:'multi', topic:'W3 · Load-time relocation', q:'Load-time relocation (rewriting addresses) has which benefit(s)?', opts:['Requires no special hardware support','Is fast at runtime (no per-access translation)','Provides strong memory protection','Allows easy relocation after loading'], correct:[0,1], explain:'Load-time rewriting needs no MMU and has no per-access cost. But it gives <strong>no protection</strong> and can\u2019t relocate once loaded. Hardware base/limit or paging is needed for protection.' },
  { type:'multi', topic:'W3 · Base & limit', q:'A base-and-limit MMU can be thought of as\u2026', opts:['A segmentation system with a single segment','A form of relocation done in hardware at access time','A paging system with many pages','Providing bounds checking via the limit register'], correct:[0,1,3], explain:'Base/limit = one relocatable, bounds-checked segment, done in hardware per access. It is <strong>not</strong> a many-page system \u2014 that\u2019s paging.' },
  { type:'multi', topic:'W3 · Fragmentation', q:'Which statements about fragmentation are correct?', opts:['Internal fragmentation is wasted space inside an allocation','External fragmentation is free space scattered in unusable gaps','Paging eliminates external fragmentation','Paging eliminates internal fragmentation'], correct:[0,1,2], explain:'Internal = waste within a block; external = scattered free gaps. Equal-size frames remove <strong>external</strong> fragmentation but <em>cause</em> internal fragmentation (partly-used last page).' },
  { type:'single', topic:'W3 · Page count', q:'If virtual addresses are <em>n</em> bits and the offset is <em>o</em> bits, the number of pages is\u2026', opts:['2<sup>o</sup>','2<sup>n</sup>','2<sup>n\u2212o</sup>','2<sup>n+o</sup>'], correct:[2], explain:'The page number occupies the top n\u2212o bits, so there are <strong>2<sup>n\u2212o</sup></strong> pages, each of 2<sup>o</sup> bytes.' },
  { type:'single', topic:'W3 · Translation', q:'In page-based translation, a virtual address is split into\u2026', opts:['A segment number and a base','A page number and an offset','A frame number and a limit','A base and a bound'], correct:[1], explain:'The virtual address = (page number, offset). The page number indexes the page table to get a frame number; the offset is added unchanged within the frame.' },
  { type:'multi', topic:'W3 · Paging advantages', q:'Page-based address translation has which advantage(s)?', opts:['Eliminates external fragmentation','Any free frame can hold any page','Needs only a single base register','Supports non-contiguous allocation'], correct:[0,1,3], explain:'Equal frames mean any frame fits any page (non-contiguous allocation, no external fragmentation). It needs a <strong>page table</strong>, not just a single base register.' },
  { type:'single', topic:'W3 · PT size', q:'For a 32-bit address space with 4KB pages and 4-byte page-table entries, a flat page table needs roughly\u2026', opts:['4 KB','4 MB','1 KB','4 GB'], correct:[1], explain:'Offset = 12 bits (4KB), so 20-bit page number \u2192 2\u00b2\u2070 = ~1,048,576 entries \u00d7 4 bytes \u2248 <strong>4 MB</strong> per process.' },
  { type:'multi', topic:'W3 · Multi-level PT', q:'Multi-level page tables are motivated by\u2026', opts:['Flat page tables taking too much space','Address spaces being large and sparsely used','The ability to omit entries for unused regions','Making every translation a single memory access'], correct:[0,1,2], explain:'Multi-level tables save space by not allocating sub-tables for unused regions of a large, sparse address space. They actually <strong>add</strong> memory accesses (one per level), which is why the TLB matters.' },
  { type:'multi', topic:'W3 · TLB', q:'Which statements about the TLB are true?', opts:['It caches recent virtual-to-physical translations','A TLB hit avoids a full page-table walk','It exploits spatial and temporal locality','It stores the actual data of recently accessed pages'], correct:[0,1,2], explain:'The TLB caches <em>translations</em> (not data). A hit skips the page-table walk; it works because of locality. The data cache (not the TLB) holds the data.' },
  { type:'single', topic:'W3 · TLB miss', q:'On a software-managed TLB (e.g. MIPS), a TLB miss is handled by\u2026', opts:['The hardware walking the page table automatically','An OS trap handler that loads the translation, then retries the instruction','Killing the process','Flushing the entire cache'], correct:[1], explain:'Software-managed TLBs raise an exception; an OS handler does the lookup, updates the TLB, and returns to <strong>retry the same instruction</strong> (unlike a syscall, which resumes at the next one).' },
  { type:'multi', topic:'W3 · Segmentation', q:'Which statements about segmentation are true?', opts:['Segments can have different sizes','It can suffer external fragmentation','Each segment can have its own protection bits','It completely eliminates fragmentation'], correct:[0,1,2], explain:'Segments are variable-sized with their own protections, but variable sizes lead to <strong>external</strong> fragmentation \u2014 the problem paging solves.' },

  // ===================== WEEK 4: Demand paging =====================
  { type:'multi', topic:'W4 · Page fault', q:'A page fault\u2026', opts:['Occurs when a referenced page isn\u2019t in physical memory','Can be used as a \u201chook\u201d for the OS to act and then resume','Always indicates a program bug','Lets the OS load the page and restart the instruction'], correct:[0,1,3], explain:'A page fault traps to the OS, which can load the page (from disk, allocate lazily, do copy-on-write\u2026) and resume. It is a <strong>mechanism</strong>, not necessarily a bug.' },
  { type:'multi', topic:'W4 · Lazy techniques', q:'Which are examples of the OS being \u201clazy\u201d to save work?', opts:['Lazy allocation (allocate frames on first access)','Copy-on-write (share until a write happens)','Lazy zeroing (one shared zero page until written)','Pre-loading the entire program before it runs'], correct:[0,1,2], explain:'Lazy allocation, copy-on-write and lazy zeroing all defer work until it\u2019s actually needed. Pre-loading everything eagerly is the <strong>opposite</strong> of lazy.' },
  { type:'single', topic:'W4 · Copy-on-write', q:'Copy-on-write means\u2026', opts:['Every write is copied to disk immediately','Shared pages are only duplicated when one party writes','Reads always trigger a copy','The OS copies the whole address space on fork'], correct:[1], explain:'After fork, parent and child share pages read-only; a page is physically copied only when one of them <strong>writes</strong> to it \u2014 avoiding copying pages that are never modified.' },
  { type:'single', topic:'W4 · AMAT', q:'Average Memory Access Time (AMAT) is given by\u2026', opts:['T_memory + (P_miss \u00d7 T_disk)','T_disk \u2212 T_memory','P_miss \u00d7 T_memory','T_memory \u00d7 T_disk'], correct:[0], explain:'AMAT = T_memory + P_miss \u00d7 T_disk. Because T_disk is enormous, even a tiny miss probability dominates the average \u2014 hence the value of high hit rates.' },
  { type:'multi', topic:'W4 · Replacement', q:'Which are page-replacement policies?', opts:['FIFO','LRU (Least Recently Used)','Optimal (MIN)','SJF'], correct:[0,1,2], explain:'FIFO, LRU and Optimal/MIN are replacement policies. SJF is a <em>CPU scheduling</em> algorithm, not page replacement.' },
  { type:'single', topic:'W4 · Optimal', q:'The Optimal (MIN) replacement policy evicts\u2026', opts:['The page used least recently','The page that will be used furthest in the future','The oldest loaded page','A random page'], correct:[1], explain:'Optimal evicts the page whose next use is furthest in the future. It\u2019s impossible to implement (needs the future) but serves as the best-case <strong>baseline</strong>.' },
  { type:'multi', topic:'W4 · Belady', q:'Which statements about Belady\u2019s anomaly are true?', opts:['It can occur with FIFO replacement','Giving more frames can increase the number of faults','LRU avoids it (stack property)','It affects the Optimal policy'], correct:[0,1,2], explain:'Belady\u2019s anomaly \u2014 more frames causing <em>more</em> faults \u2014 affects FIFO. LRU and Optimal are stack algorithms and are immune.' },
  { type:'single', topic:'W4 · Clock', q:'The Clock (second-chance) algorithm approximates\u2026', opts:['FIFO','Optimal','LRU','Random'], correct:[2], explain:'Clock approximates LRU cheaply using a reference/use bit and a circular scan, giving recently-used pages a \u201csecond chance\u201d before eviction.' },
  { type:'multi', topic:'W4 · Working set', q:'Which statements about working sets and thrashing are true?', opts:['The working set is the set of pages a process is actively using','Thrashing happens when memory can\u2019t hold the working sets','Thrashing causes constant paging and low throughput','Giving every process an equal share always prevents thrashing'], correct:[0,1,2], explain:'When total memory can\u2019t hold all working sets, the system thrashes (constant paging, little progress). Equal shares can <strong>worsen</strong> it; sometimes suspending a process is better.' },
  { type:'single', topic:'W4 · Swapping', q:'Swapping refers to\u2026', opts:['Exchanging two registers','Moving pages between physical memory and disk','Switching CPU cores','Reordering instructions'], correct:[1], explain:'Swapping moves pages between RAM and backing store (disk), creating the illusion of more memory than physically exists \u2014 the basis of demand paging / virtual memory.' },

  // ===================== WEEK 5: User-space (malloc, stack, files, I/O) =====================
  { type:'multi', topic:'W5 · malloc', q:'Which statements about malloc are true?', opts:['It is library code running inside the user process','It parcels small pieces out of large OS-provided chunks','It is a system call handled entirely by the kernel','It tracks which parts of the heap are free or used'], correct:[0,1,3], explain:'malloc is <strong>library</strong> code in the process; it sub-allocates from heap chunks the OS gave it and tracks free/used. It only calls the kernel (via brk/mmap) when it needs more raw memory.' },
  { type:'multi', topic:'W5 · Fragmentation layers', q:'Why are there \u201ctwo layers\u201d of allocation?', opts:['The OS allocates pages to the process','malloc sub-allocates within those pages','Each layer has its own fragmentation','The CPU allocates registers as a third layer for malloc'], correct:[0,1,2], explain:'Layer 1: the OS gives pages to the process. Layer 2: malloc carves small pieces from them. Each has its own fragmentation. Registers are not part of this allocation story.' },
  { type:'multi', topic:'W5 · Free list', q:'Which statements about a free list are true?', opts:['It can be threaded through the free space itself','Each node records a size and a pointer to the next free area','Adjacent free blocks are often coalesced','It must be stored entirely in the kernel'], correct:[0,1,2], explain:'A free list lives in the heap\u2019s free space, each node holding size + next pointer; adjacent frees are coalesced to fight fragmentation. It\u2019s a user-space structure, not in the kernel.' },
  { type:'single', topic:'W5 · Fit policy', q:'Compared with best-fit, first-fit allocation is\u2026', opts:['Slower but wastes less space','Faster because it stops at the first suitable block','Guaranteed to avoid fragmentation','Only usable with paging'], correct:[1], explain:'First-fit stops at the first block big enough (faster); best-fit scans all blocks for the tightest fit (less waste per allocation but slower, and can leave tiny fragments).' },
  { type:'multi', topic:'W5 · brk vs mmap', q:'Which statements about brk and mmap are true?', opts:['brk moves the program break to grow the heap','mmap can map memory anywhere, not just at the break','mmap has no single contended resource, better for threads','brk can map a named file into memory'], correct:[0,1,2], explain:'brk moves the single program break; mmap is flexible (anywhere, non-contiguous, thread-friendly) and can map <strong>named files</strong> \u2014 brk cannot.' },
  { type:'single', topic:'W5 · Stack frame', q:'On x86-64, the first things pushed in a typical stack frame are\u2026', opts:['Local variables only','The return address and saved frame pointer','The heap pointer','The page table base'], correct:[1], explain:'A frame typically starts with the saved return address and caller\u2019s frame pointer, followed by saved registers and locals. This chain lets you \u201cwalk\u201d the stack for a backtrace.' },
  { type:'multi', topic:'W5 · Buffer overflow', q:'Which statements about stack-smashing buffer overflows are true?', opts:['Unbounded input can overwrite the return address','Overwriting the return address can hijack control flow','C arrays are bounds-checked by default','Java prevents this with array bounds checks'], correct:[0,1,3], explain:'Over-long input past a buffer can overwrite the saved return address, redirecting execution. C does <strong>not</strong> bounds-check by default; Java does (throwing an exception), preventing the overflow.' },
  { type:'multi', topic:'W5 · File descriptors', q:'Which statements about file descriptors are true?', opts:['They are small integers indexing a kernel table','fd 0, 1, 2 are stdin, stdout, stderr by default','They can refer to files, sockets, pipes and devices','They directly contain the memory address of the file'], correct:[0,1,2], explain:'An fd is an opaque small integer indexing a kernel-controlled table; 0/1/2 are the standard streams; it can name many object types. It is <strong>not</strong> a memory address \u2014 that\u2019s the whole point of an opaque handle.' },
  { type:'single', topic:'W5 · Handles', q:'Why does the OS hand out opaque handles instead of memory addresses?', opts:['Addresses are too short','Processes don\u2019t share memory with the OS and some objects have no address','Handles are easier to type','It is required by C'], correct:[1], explain:'Processes don\u2019t share the kernel\u2019s memory, can\u2019t use device-level IDs, and some objects (threads, processes) have no address at all \u2014 so an opaque handle into a kernel table is used.' },
  { type:'multi', topic:'W5 · IPC', q:'Which are inter-process communication mechanisms?', opts:['Pipes','Sockets','Shared memory via mmap(MAP_SHARED)','Private per-thread registers'], correct:[0,1,2], explain:'Pipes, sockets and shared memory are IPC channels. Registers are private CPU state, not an IPC mechanism.' },
  { type:'single', topic:'W5 · Shared memory', q:'Why can shared memory be faster than pipes for IPC?', opts:['It compresses the data','It avoids a system call on every exchange','It uses the GPU','It encrypts automatically'], correct:[1], explain:'With shared memory, both processes read/write the same physical frames directly \u2014 no syscall (mode-switch) per message, unlike read/write on a pipe.' },
  { type:'multi', topic:'W5 · I/O evolution', q:'Order-of-efficiency aside, which describe real I/O approaches?', opts:['Programmed I/O with polling keeps the CPU busy waiting','Interrupt-driven I/O lets the CPU work until the device signals completion','DMA lets the device transfer data to memory by itself','Polling is always more efficient than interrupts'], correct:[0,1,2], explain:'Polling wastes CPU; interrupts free it until completion; DMA offloads the transfer entirely (one interrupt at the end). Polling is generally <strong>less</strong> efficient than interrupts for slow devices.' },
  { type:'single', topic:'W5 · Timer', q:'How do timer interrupts relate to scheduling?', opts:['They have no relation','A timer interrupt lets the OS regain control and run the scheduler','They replace the need for a scheduler','They only matter for I/O devices'], correct:[1], explain:'A programmable timer fires periodically; its handler calls the scheduler to possibly switch processes \u2014 this is exactly how preemptive (e.g. Round Robin) scheduling works.' },

  // ===================== WEEK 7: Security =====================
  { type:'single', topic:'W7 · Security vs FT', q:'Security differs from fault-tolerance because security assumes\u2026', opts:['Accidental errors only','An active, malicious adversary','Hardware never fails','Programs are always correct'], correct:[1], explain:'Security is <strong>adversarial</strong> \u2014 someone is actively trying to subvert the system. Fault-tolerance deals with accidental errors/incompetence. They differ in practice.' },
  { type:'single', topic:'W7 · Mechanism vs policy', q:'In access control, the OS provides the ____ and users decide the ____.', opts:['policy; mechanism','mechanism; policy','lock; key','process; thread'], correct:[1], explain:'The OS provides flexible <strong>mechanisms</strong> able to express many policies; the users decide the specific <strong>policy</strong> (who may access what).' },
  { type:'multi', topic:'W7 · Unix open()', q:'In Unix, permission checking\u2026', opts:['Happens at open() time','Is re-done on every read()/write()','Means holding an fd is enough afterwards','Makes revocation of an already-open fd hard'], correct:[0,2,3], explain:'Unix checks permissions at <strong>open()</strong> only; afterwards the fd suffices (cost amortised, delegation possible) but revoking an already-open fd is hard. read/write do <strong>not</strong> re-check.' },
  { type:'multi', topic:'W7 · ACLs', q:'Which statements about Access Control Lists are true?', opts:['They are stored with the object','Unix user/group/other bits are a limited ACL','Authority is ambient (based on who you are)','They are easy to delegate fine-grained access with'], correct:[0,1,2], explain:'ACLs live on the object, express ambient authority, and Unix permission bits are a simple ACL. They are <strong>hard</strong> to delegate finely \u2014 that\u2019s a strength of capabilities.' },
  { type:'multi', topic:'W7 · Capabilities', q:'Which statements about capabilities are true?', opts:['They are stored with the subject','A Unix file descriptor is an example of a capability','They make delegation easy','They are easy to revoke'], correct:[0,1,2], explain:'Capabilities are held by the subject (like an fd: an <access,object> pair), making delegation easy. They are <strong>hard to revoke</strong> and hard to audit \u2014 the trade-off versus ACLs.' },
  { type:'single', topic:'W7 · Ambient vs designated', q:'\u201cAmbient authority\u201d means\u2026', opts:['Authority you must explicitly present, like a key','Authority that applies automatically based on your identity','A type of encryption','A scheduling policy'], correct:[1], explain:'Ambient authority applies automatically from who you are (e.g. your user ID), as with ACLs. Capabilities use <strong>designated</strong> authority \u2014 you must present the specific capability.' },
  { type:'multi', topic:'W7 · CIA', q:'Which are part of the core security properties?', opts:['Confidentiality','Integrity','Availability','Compilability'], correct:[0,1,2], explain:'The CIA triad: Confidentiality (no unauthorised disclosure), Integrity (no unauthorised modification), Availability (service not denied). \u201cCompilability\u201d is not a security property.' },
  { type:'single', topic:'W7 · DoS', q:'A fork bomb is primarily an attack on\u2026', opts:['Confidentiality','Integrity','Availability','Authenticity'], correct:[2], explain:'A fork bomb exhausts resources to deny service to others \u2014 an <strong>availability</strong> attack. Defences include per-user resource limits.' },
  { type:'single', topic:'W7 · Least privilege', q:'The principle of least privilege says a program should\u2026', opts:['Run as root for convenience','Have only the authority it actually needs','Never make system calls','Always run in a virtual machine'], correct:[1], explain:'Least privilege: grant only the minimum authority needed, so an exploited program can do limited damage. Running everything as root violates it.' },
  { type:'multi', topic:'W7 · setuid', q:'Which statements about setuid programs are true?', opts:['A setuid program runs with the owner\u2019s privileges, not the invoker\u2019s','setuid-root programs are especially dangerous if buggy','seteuid() can drop privileges to the invoker\u2019s','setuid has no security implications'], correct:[0,1,2], explain:'setuid runs with the file owner\u2019s privileges; setuid-root is dangerous (full power if exploited); seteuid() can drop privileges. It clearly <strong>does</strong> have security implications.' },
  { type:'multi', topic:'W7 · Confused deputy', q:'A confused deputy attack involves\u2026', opts:['Code acting under two or more authorities','A crafty input tricking it into using the wrong authority','PwnKit/pkexec as a real-world example','Always requiring physical access'], correct:[0,1,2], explain:'A confused deputy holds multiple authorities and is tricked into using the wrong (more privileged) one. PwnKit (CVE-2021-4034) is the canonical example. No physical access needed.' },
  { type:'single', topic:'W7 · PwnKit', q:'The key low-level vulnerability exploited by PwnKit was\u2026', opts:['A SQL injection','An out-of-bounds (buffer overflow) write','A weak password','A timing channel'], correct:[1], explain:'PwnKit used an out-of-bounds write (a buffer overflow) to reintroduce an unsafe environment variable, ultimately running attacker code as root via the logging/charset machinery.' },
  { type:'multi', topic:'W7 · Auth factors', q:'Which are authentication factors?', opts:['Something you know','Something you have','Something you are','Something you compile'], correct:[0,1,2], explain:'The three factors: know (password), have (key/phone), are (biometric). Combining them is multi-factor authentication.' },
  { type:'multi', topic:'W7 · Passwords', q:'Which are good password-handling practices?', opts:['Store a cryptographic hash, not the password','Rate-limit login attempts','Forbid dictionary words','Store passwords in plaintext for convenience'], correct:[0,1,2], explain:'Store hashes (never plaintext), rate-limit brute force, forbid dictionary words. Plaintext storage is the no-excuses failure behind most mass leaks.' },
  { type:'single', topic:'W7 · Hashing', q:'Storing a cryptographic hash of a password rather than the password itself means\u2026', opts:['The password can be decrypted by the server','Knowing the stored hashes doesn\u2019t directly reveal passwords','Logins become impossible','It is the same as encrypting the password'], correct:[1], explain:'A hash is one-way \u2014 you check f(input)==stored f(password) without ever storing or recovering the password. It is <strong>not</strong> the same as (reversible) encryption.' },
  { type:'multi', topic:'W7 · Crypto', q:'Which statements about ciphers are true?', opts:['A cipher is a pair (E, D) of encrypt/decrypt functions','Security comes from a secret key, not a secret algorithm','Symmetric ciphers use the same key to encrypt and decrypt','RSA is a symmetric cipher'], correct:[0,1,2], explain:'Ciphers are E/D parameterised by a secret <strong>key</strong> (Kerckhoffs\u2019s principle). Symmetric = same key both ways. RSA is <strong>asymmetric</strong> (public/private key pair).' },
  { type:'single', topic:'W7 · Asymmetric', q:'In public-key cryptography, to send Bob a confidential message you encrypt with\u2026', opts:['Bob\u2019s private key','Bob\u2019s public key','Your own private key','A shared password'], correct:[1], explain:'Encrypt with Bob\u2019s <strong>public</strong> key; only Bob\u2019s private key can decrypt. (RSA is slow, so it\u2019s typically used to exchange a symmetric session key.)' },
  { type:'single', topic:'W7 · Hash function', q:'A cryptographic hash function must make it infeasible to\u2026', opts:['Compute the hash quickly','Find an input producing a given hash output','Produce a fixed-size output','Use it for passwords'], correct:[1], explain:'Given h(m) it must be infeasible to find m (preimage) or any m\u2032 with the same hash (collision). It should still be fast to compute and produce fixed-size output.' },

  // ===================== WEEK 8: Unix history & microkernels =====================
  { type:'single', topic:'W8 · fork()', q:'What does fork() return?', opts:['0 in both parent and child','The child\u2019s PID in the parent, 0 in the child','The parent\u2019s PID in the child, 0 in the parent','Always the same value'], correct:[1], explain:'fork() is called once, returns twice: child\u2019s PID in the parent, 0 in the child (negative on failure). That return value is how code tells which process it\u2019s in.' },
  { type:'multi', topic:'W8 · fork/exec', q:'Which statements about fork and exec are true?', opts:['fork duplicates the current process','exec replaces the process image with a new program','Between fork and exec the child can set up fds/pipes','exec creates a brand-new process'], correct:[0,1,2], explain:'fork duplicates; exec <strong>replaces</strong> the calling process with a new program (it does not create a new process). The gap between them lets the child configure fds/pipes/env.' },
  { type:'single', topic:'W8 · fork tree', q:'After 3 successive fork() calls (no exits), how many processes exist?', opts:['3','6','8','4'], correct:[2], explain:'Each fork doubles the process count: 2\u00b3 = <strong>8</strong> processes, because every existing process executes the next fork.' },
  { type:'multi', topic:'W8 · Everything is a file', q:'\u201cEverything is a file\u201d in Unix means\u2026', opts:['Devices appear as special files','Commands are just executable files','Pipes are accessed via file descriptors','Every concept is genuinely a perfect fit for the file model'], correct:[0,1,2], explain:'Devices, commands and even pipes use the file/fd abstraction. But not everything fits perfectly \u2014 e.g. seek makes no sense for audio; ioctl is the catch-all \u201cdoesn\u2019t fit\u201d operation.' },
  { type:'multi', topic:'W8 · Microkernel', q:'Which statements about microkernels are true?', opts:['Drivers and filesystems run as separate server processes','The microkernel keeps only basic IPC and interrupt handling','They improve fault isolation and least privilege','They eliminate all IPC overhead'], correct:[0,1,2], explain:'Microkernels push services into isolated servers, keeping the kernel minimal \u2014 better fault isolation/least privilege. The cost is <strong>increased</strong> IPC overhead from crossing protection boundaries.' },
  { type:'single', topic:'W8 · Monolithic', q:'A monolithic kernel (like Linux) is characterised by\u2026', opts:['Drivers and services running in separate user processes','Filesystems, drivers, scheduling all running together in kernel mode','Having no device drivers','Being unable to multitask'], correct:[1], explain:'In a monolithic kernel, filesystems, drivers, scheduling and memory management all run together in kernel mode \u2014 fast, but a bug anywhere can crash everything.' },
  { type:'single', topic:'W8 · Tanenbaum debate', q:'The Tanenbaum\u2013Torvalds debate was about\u2026', opts:['Which language to use','Microkernel vs monolithic kernel design','Open vs closed source','Paging vs segmentation'], correct:[1], explain:'In 1992 Tanenbaum argued microkernels had \u201cwon\u201d and called Linux\u2019s monolithic design obsolete. History favoured Linux \u2014 development model and pragmatism beat architectural elegance.' },
  { type:'single', topic:'W8 · IPC cost', q:'The main performance problem with microkernels is\u2026', opts:['Too little memory','IPC overhead from crossing protection boundaries','Lack of device drivers','Slow compilation'], correct:[1], explain:'Splitting services into processes means many more protection-boundary crossings (IPC). L4-style architecture-aware IPC optimisation greatly reduced this.' },

  // ===================== WEEK 9: Java threads & memory model =====================
  { type:'multi', topic:'W9 · Creating threads', q:'Which are valid ways to create a thread in Java?', opts:['Extend Thread and override run()','Implement Runnable and pass it to a Thread','Use a lambda as a Runnable','Call run() directly to start a new thread'], correct:[0,1,2], explain:'Extend Thread, implement Runnable, or use a lambda. You must call <strong>start()</strong>, not run() \u2014 calling run() directly just executes it in the current thread.' },
  { type:'single', topic:'W9 · start vs run', q:'To begin concurrent execution of a thread you call\u2026', opts:['run()','start()','execute()','go()'], correct:[1], explain:'start() asks the JVM to schedule the thread and call run() on it. Calling run() yourself runs it synchronously in the current thread \u2014 no concurrency.' },
  { type:'multi', topic:'W9 · Runnable vs Thread', q:'Why prefer implementing Runnable over extending Thread?', opts:['It leaves you free to extend another class','You can pass one Runnable to several threads (sharing behaviour)','It decouples the task from the thread machinery','Runnable threads run faster intrinsically'], correct:[0,1,2], explain:'Runnable keeps single-inheritance free, lets you share one behaviour object across threads, and decouples task from thread. There is <strong>no</strong> intrinsic speed difference.' },
  { type:'multi', topic:'W9 · Lifecycle', q:'Which statements about thread lifecycle are true?', opts:['sleep() pauses a thread (TIMED_WAITING)','join() makes the caller wait for another thread to finish','A daemon thread dies when the main/non-daemon threads end','Thread.stop() is the recommended way to stop threads'], correct:[0,1,2], explain:'sleep pauses (TIMED_WAITING); join waits for completion; daemon threads end with the program. stop() is <strong>deprecated</strong> \u2014 use a boolean flag instead.' },
  { type:'single', topic:'W9 · Independence', q:'Which is true about the Main thread?', opts:['It owns all other threads','It is \u201cjust another thread\u201d; the JVM runs until all non-daemon threads finish','It must exit last','It cannot create other threads'], correct:[1], explain:'Main is just another thread; threads are independent peers. The JVM keeps running while any non-daemon thread lives \u2014 even after Main exits.' },
  { type:'multi', topic:'W9 · Memory model', q:'In the Java memory model, which are true?', opts:['Local primitives and references live on the thread\u2019s stack','Objects live on the shared heap','An object\u2019s fields live on the heap with the object','Each thread has a private copy of every object'], correct:[0,1,2], explain:'Locals/refs are per-thread (stack); objects and their fields are on the shared heap. Threads can <strong>share</strong> objects (no automatic private copies) \u2014 the source of races.' },
  { type:'single', topic:'W9 · Atomicity', q:'Why is counter++ not atomic?', opts:['It uses floating point','It is three steps: read, increment, write','It calls the OS','It allocates memory'], correct:[1], explain:'counter++ = READ the value, INCREMENT it, WRITE it back. Two threads interleaving these steps can lose an update.' },
  { type:'single', topic:'W9 · Lost update', q:'A lost update occurs when\u2026', opts:['A file is deleted','Two threads read the same value, increment, and one overwrites the other','The disk fails','A thread sleeps too long'], correct:[1], explain:'Both threads read the same old value, each increments locally, and the later write overwrites the earlier \u2014 so two increments produce only one net change.' },
  { type:'multi', topic:'W9 · Race condition', q:'Which statements about race conditions are true?', opts:['The result depends on thread timing, not program logic','They require shared mutable state','They give non-deterministic results','They occur even when threads share nothing'], correct:[0,1,2], explain:'A race needs <strong>shared mutable state</strong>; the outcome depends on timing and is non-deterministic. With no sharing there is no race.' },
  { type:'single', topic:'W9 · States', q:'A sleeping Java thread is in which state?', opts:['RUNNABLE','BLOCKED','TIMED_WAITING','TERMINATED'], correct:[2], explain:'Thread.sleep(ms) puts the thread in TIMED_WAITING. BLOCKED is waiting for a lock; WAITING is indefinite (e.g. join with no timeout).' },

  // ===================== WEEK 10: Synchronization =====================
  { type:'multi', topic:'W10 · Two problems', q:'Concurrency requires solving which two distinct problems?', opts:['Mutual exclusion (atomicity)','Visibility of updates across threads','Compilation speed','Disk scheduling'], correct:[0,1], explain:'The two problems: mutual exclusion (stop mid-operation interleaving) and visibility (make updates seen across caches). Compilation and disk scheduling are unrelated.' },
  { type:'single', topic:'W10 · Critical section', q:'A critical section is\u2026', opts:['Any loop','Code that only one thread at a time should execute','The main method','A section of the heap'], correct:[1], explain:'A critical section is code that must be executed by only one thread at a time to avoid incorrect/unpredictable results; it is protected by mutual exclusion (locks).' },
  { type:'multi', topic:'W10 · synchronized', q:'Which statements about a synchronized method are true?', opts:['It makes the whole method a critical section','It locks on the this object implicitly','While held, other synchronized methods on that object are blocked','It locks only that single method, allowing other synchronized methods to run'], correct:[0,1,2], explain:'A synchronized method locks on <code>this</code>; holding that intrinsic lock blocks <strong>all</strong> synchronized methods on the object \u2014 not just the one method.' },
  { type:'multi', topic:'W10 · Intrinsic lock', q:'Which statements about intrinsic locks are true?', opts:['Every Java object has one','It is acquired on entering a synchronized region and released on exit','If a thread never releases it, others block forever','Primitives like int have their own intrinsic lock'], correct:[0,1,2], explain:'Every <strong>object</strong> has an intrinsic lock (monitor), acquired/released around synchronized regions; failing to release blocks others forever. Primitives are not objects and have no lock.' },
  { type:'single', topic:'W10 · synchronized block', q:'A synchronized block is preferable to a synchronized method when\u2026', opts:['You want to lock the whole method','Only part of the method touches shared state','You never want to lock anything','The method has no parameters'], correct:[1], explain:'A block locks only the necessary part (and lets you choose which object to lock on), avoiding needless locking of code \u2014 like local-only computations \u2014 that doesn\u2019t touch shared state.' },
  { type:'single', topic:'W10 · Thread safety', q:'An immutable object is\u2026', opts:['Never useful in concurrency','Inherently thread-safe because its state can\u2019t change','Always slower','Impossible in Java'], correct:[1], explain:'If state can never change, no thread can observe an inconsistent value, so immutable objects are <strong>inherently thread-safe</strong> \u2014 no locking needed.' },
  { type:'multi', topic:'W10 · Memory levels', q:'Which statements about the memory hierarchy and visibility are true?', opts:['Each CPU core has its own registers and cache','A value updated in one core\u2019s cache may be stale in another\u2019s','Caches must be flushed to RAM for updates to be globally visible','Mutual exclusion alone solves the visibility problem'], correct:[0,1,2], explain:'Per-core caches can hold stale copies; flushing to RAM is needed for global visibility. Mutual exclusion alone does <strong>not</strong> fix visibility \u2014 you need volatile or synchronized\u2019s flush.' },
  { type:'multi', topic:'W10 · volatile', q:'Which statements about volatile are true?', opts:['It forces writes to flush to main memory','It forces reads to come from main memory','It guarantees mutual exclusion / atomicity','One volatile flush also flushes other visible variables'], correct:[0,1,3], explain:'volatile guarantees visibility (flush on write, read from RAM) and Java\u2019s visibility guarantee flushes all visible vars. It does <strong>not</strong> provide atomicity \u2014 counter++ on a volatile is still a race.' },
  { type:'single', topic:'W10 · synchronized visibility', q:'Besides mutual exclusion, a synchronized block also provides\u2026', opts:['Nothing else','Visibility: refresh from RAM on entry, flush to RAM on exit','Faster execution','Automatic deadlock prevention'], correct:[1], explain:'synchronized fixes <strong>both</strong> problems: on entry it refreshes visible variables from RAM, on exit it flushes them \u2014 so it gives mutual exclusion and visibility.' },
  { type:'single', topic:'W10 · Reordering', q:'The happens-before guarantee prevents\u2026', opts:['Threads from running in parallel','Statements before a volatile write from being reordered after it','Use of synchronized blocks','Garbage collection'], correct:[1], explain:'happens-before stops the compiler/CPU from moving a statement that precedes a volatile write (or crosses a synchronized boundary) to after it \u2014 preventing dangerous reordering.' },

  // ===================== WEEK 11: Deadlock & semaphores =====================
  { type:'multi', topic:'W11 · ReentrantLock', q:'Which statements about ReentrantLock are true?', opts:['You must explicitly lock() and unlock()','unlock() should go in a finally block','It can lock and unlock across different methods','It releases automatically when the method returns'], correct:[0,1,2], explain:'ReentrantLock is explicit (lock/unlock), so unlock belongs in finally (else an exception leaves it locked forever). Unlike synchronized, it does <strong>not</strong> release automatically.' },
  { type:'single', topic:'W11 · Reentrancy', q:'A reentrant lock allows\u2026', opts:['Two different threads to hold it at once','A thread that holds it to acquire it again without blocking','Only one acquisition ever','Locks to be skipped'], correct:[1], explain:'Reentrancy lets the holding thread re-acquire its own lock \u2014 essential when a synchronized method calls another synchronized method on the same object (else self-deadlock).' },
  { type:'multi', topic:'W11 · synchronized vs Lock', q:'What can ReentrantLock do that synchronized cannot?', opts:['Try to acquire without blocking (tryLock)','Time-limited or interruptible acquisition','Guarantee fairness (arrival order)','Lock and unlock within a single expression automatically'], correct:[0,1,2], explain:'ReentrantLock adds tryLock, timed/interruptible acquisition, fairness and introspection. The automatic single-expression scoping is the convenience of <strong>synchronized</strong>, not ReentrantLock.' },
  { type:'multi', topic:'W11 · Deadlock conditions', q:'Which are the four necessary conditions for deadlock?', opts:['Mutual exclusion','Hold and wait','No preemption','Circular wait'], correct:[0,1,2,3], explain:'All four Coffman conditions \u2014 mutual exclusion, hold-and-wait, no preemption, circular wait \u2014 must hold simultaneously. Breaking any one prevents deadlock.' },
  { type:'single', topic:'W11 · Breaking deadlock', q:'To prevent deadlock you must\u2026', opts:['Satisfy all four conditions','Break at least one of the four conditions','Add more threads','Increase the time quantum'], correct:[1], explain:'Since all four conditions are necessary together, breaking <strong>any one</strong> of them prevents deadlock \u2014 the basis of every avoidance strategy.' },
  { type:'multi', topic:'W11 · Dining philosophers', q:'Which statements about the dining philosophers problem are true?', opts:['Each philosopher needs two forks to eat','All grabbing the left fork at once causes circular wait','It can deadlock and starve everyone','Adding more forks than philosophers is the only fix'], correct:[0,1,2], explain:'Two forks needed; simultaneous left-grabs create a circular wait \u2192 deadlock/starvation. The classic fix isn\u2019t more forks but breaking symmetry (e.g. last philosopher grabs right first) or using tryLock.' },
  { type:'single', topic:'W11 · Lock ordering', q:'The bank-transfer deadlock is fixed by\u2026', opts:['Removing all locks','Acquiring locks in a consistent global order (e.g. by account id)','Using more threads','Making transfers slower'], correct:[1], explain:'Imposing a fixed global lock-acquisition order (e.g. always lock the lower account id first) breaks the circular-wait condition, so no cycle can form.' },
  { type:'single', topic:'W11 · tryLock fix', q:'Using tryLock() in dining philosophers helps by\u2026', opts:['Guaranteeing fairness','Letting a philosopher give up the first fork instead of holding-and-waiting','Removing mutual exclusion','Adding more forks'], correct:[1], explain:'tryLock lets a philosopher who can\u2019t get the second fork put the first one back instead of holding-and-waiting \u2014 breaking the hold-and-wait condition.' },
  { type:'multi', topic:'W11 · Semaphores', q:'Which statements about semaphores are true?', opts:['A counting semaphore allows up to N concurrent holders','acquire() decrements the permit count and blocks at zero','release() returns a permit','A binary semaphore (0/1) acts like a lock'], correct:[0,1,2,3], explain:'A counting semaphore allows N holders; acquire takes a permit (blocking at 0); release returns one; a 0/1 binary semaphore behaves like a lock. All four are correct.' },
  { type:'single', topic:'W11 · Semaphore use', q:'A semaphore initialised to 5 is a good fit for\u2026', opts:['Allowing exactly one thread at a time','Limiting concurrent access to a 5-connection database','Disabling concurrency','Replacing the scheduler'], correct:[1], explain:'A counting semaphore with 5 permits lets up to 5 threads use a resource at once \u2014 e.g. a DB that supports 5 concurrent connections. (One permit = a lock.)' },

  // ===================== Cross-cutting / mixed =====================
  { type:'multi', topic:'X · Interrupts', q:'Which of these are driven by interrupts?', opts:['I/O completion notifications','Preemptive scheduling (via timer)','Page faults handling','Compiling a program'], correct:[0,1,2], explain:'Interrupts underlie I/O completion, timer-based preemption and (as traps) page-fault handling. Compilation is just a user program running.' },
  { type:'single', topic:'X · Copy-on-write', q:'Copy-on-write connects which two topics?', opts:['Scheduling and security','Demand paging (lazy) and fork()','Caches and the TLB','Pipes and sockets'], correct:[1], explain:'CoW links lazy demand paging (W4) with fork (W8): after fork, parent and child share pages until one writes, then a copy is made.' },
  { type:'single', topic:'X · fd = capability', q:'A Unix file descriptor is a good example of\u2026', opts:['An access control list','A capability','A page table entry','A semaphore'], correct:[1], explain:'An fd bundles an object reference with access rights (set at open) and is held by the subject \u2014 the defining shape of a capability (linking W5, W7, W8).' },
  { type:'multi', topic:'X · Fragmentation recurs', q:'Where does fragmentation appear in this course?', opts:['Segmentation (external)','Paging (internal)','malloc heap (both)','CPU scheduling'], correct:[0,1,2], explain:'Fragmentation recurs: segmentation (external), paging (internal), and malloc\u2019s heap (both kinds). Scheduling is a separate concern.' },
  { type:'single', topic:'X · LDE underpins', q:'Limited direct execution is the foundation for\u2026', opts:['Only file systems','Memory protection, preemptive scheduling and security','Only the GUI','Only compilation'], correct:[1], explain:'LDE (user/kernel mode + interrupts) underpins memory protection, the ability to preempt and schedule, and the enforcement of security \u2014 it threads through the whole course.' },
  { type:'multi', topic:'X · Visibility vs mutex', q:'Which tool fixes which concurrency problem?', opts:['volatile fixes visibility','synchronized fixes both mutual exclusion and visibility','volatile fixes mutual exclusion','locks (synchronized) fix mutual exclusion'], correct:[0,1,3], explain:'volatile = visibility only; synchronized/locks = mutual exclusion (and synchronized also gives visibility). volatile does <strong>not</strong> provide mutual exclusion.' },
  { type:'single', topic:'X · Page fault cost', q:'Page faults are costly mainly because\u2026', opts:['They use the GPU','Disk access is enormously slower than memory','They require recompilation','They reset the CPU'], correct:[1], explain:'Servicing a fault from disk costs millions of cycles versus a memory access, which is why AMAT is dominated by even a small miss rate.' },
  { type:'multi', topic:'X · Kernel concurrency', q:'Which statements about kernel concurrency (e.g. Linux) are true?', opts:['The kernel is itself a highly concurrent program','Linux moved from a big kernel lock to fine-grained locking','RCU is a lock-free technique favouring readers','Kernels never need synchronization'], correct:[0,1,2], explain:'The kernel runs many threads across cores plus interrupts; Linux moved from the BKL to fine-grained and lock-free techniques like RCU (great for read-heavy data). Kernels very much <strong>do</strong> need synchronization.' },
];

  const MOCK_COUNT = 10;          // questions per exam attempt
  let mockQuestions = [];         // the current sampled subset
  const mockState = {};           // qIndex -> {selected:Set, checked:bool, correct:bool}

  function sampleMockQuestions() {
    // Fisher-Yates shuffle a copy of the bank, take the first MOCK_COUNT
    const pool = mockQuestionBank.slice();
    for (let i = pool.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [pool[i], pool[j]] = [pool[j], pool[i]];
    }
    mockQuestions = pool.slice(0, MOCK_COUNT);
    for (const k in mockState) delete mockState[k];
  }

  function renderMock() {
    const container = document.getElementById('mock-container');
    if (!container) return;
    container.innerHTML = '';
    mockQuestions.forEach((q, qi) => {
      if (!mockState[qi]) mockState[qi] = { selected: new Set(), checked: false, correct: false };
      const st = mockState[qi];
      const div = document.createElement('div');
      div.className = 'mock-q';
      const typeLabel = q.type === 'single' ? 'Select one' : 'Select all that apply';
      let html = `<div class="mock-q-head">
        <span class="mock-q-num">Question ${qi+1}</span>
        <span class="mock-q-meta"><span class="mock-q-type">${typeLabel}</span> <span class="mock-tag">${q.topic}</span> &nbsp;5 marks</span>
      </div>
      <div class="mock-q-text">${q.q}</div>
      <div class="mock-opts">`;
      q.opts.forEach((opt, oi) => {
        const letter = String.fromCharCode(97 + oi);
        let cls = 'mock-opt' + (q.type === 'single' ? ' radio' : '');
        if (st.selected.has(oi)) cls += ' selected';
        if (st.checked) {
          const isCorrect = q.correct.includes(oi);
          const isSelected = st.selected.has(oi);
          if (isSelected && isCorrect) cls += ' correct';
          else if (isSelected && !isCorrect) cls += ' incorrect';
          else if (!isSelected && isCorrect) cls += ' missed';
        }
        const mark = st.checked
          ? (q.correct.includes(oi) ? '\u2713' : (st.selected.has(oi) ? '\u2717' : ''))
          : (st.selected.has(oi) ? (q.type==='single'?'\u25cf':'\u2713') : '');
        html += `<div class="${cls}" onclick="mockSelect(${qi},${oi})">
          <span class="opt-box">${mark}</span>
          <span><span class="opt-letter">${letter}.</span>${opt}</span>
        </div>`;
      });
      html += `</div>`;
      html += `<button class="tool-btn mock-q-btn" onclick="mockCheck(${qi})">${st.checked ? 'Re-check' : 'Check answer'}</button>`;
      const verdictClass = st.correct ? 'me-correct' : 'me-wrong';
      const verdictText = st.correct ? '\u2713 Correct \u2014 5/5 marks' : '\u2717 Not quite \u2014 0/5 (all-or-nothing)';
      html += `<div class="mock-explain ${st.checked ? 'show' : ''}">
        <div class="me-verdict ${verdictClass}">${verdictText}</div>
        ${q.explain}
      </div>`;
      div.innerHTML = html;
      container.appendChild(div);
    });
    updateMockScore();
  }

  function mockSelect(qi, oi) {
    const q = mockQuestions[qi];
    const st = mockState[qi];
    if (st.checked) return; // lock after checking until re-check
    if (q.type === 'single') {
      st.selected = new Set([oi]);
    } else {
      if (st.selected.has(oi)) st.selected.delete(oi);
      else st.selected.add(oi);
    }
    renderMock();
  }

  function mockCheck(qi) {
    const q = mockQuestions[qi];
    const st = mockState[qi];
    if (st.checked) { st.checked = false; renderMock(); return; } // re-check toggles back to editing
    if (st.selected.size === 0) return;
    // all-or-nothing: selected set must exactly equal correct set
    const correctSet = new Set(q.correct);
    st.correct = st.selected.size === correctSet.size && [...st.selected].every(x => correctSet.has(x));
    st.checked = true;
    renderMock();
  }

  function updateMockScore() {
    let score = 0, answered = 0;
    mockQuestions.forEach((q, qi) => {
      const st = mockState[qi];
      if (st && st.checked) { answered++; if (st.correct) score += 5; }
    });
    const scoreEl = document.getElementById('mock-score');
    const detailEl = document.getElementById('mock-detail');
    const progEl = document.getElementById('mock-progress');
    if (scoreEl) scoreEl.textContent = `${score} / 50`;
    if (detailEl) detailEl.textContent = `${answered} of 10 answered`;
    if (progEl) progEl.style.width = (answered * 10) + '%';
  }

  function resetMock() {
    sampleMockQuestions();   // pick a fresh random 10 each reset
    renderMock();
  }

  /* The mock exam builds its paper the first time the section is opened, so
     the questions are not drawn until someone actually wants them. The engine's
     showWeek is generic, so the module registers the hook rather than editing it. */
  NAV.onShow.push(function (id) {
    if (id !== 'mock') return;
    if (mockQuestions.length === 0) sampleMockQuestions();
    renderMock();
  });

  window.mockQuestionBank = mockQuestionBank;
